top_srcdir   = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
top_builddir = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
srcdir       = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules/core
builddir     = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules/core
VPATH        = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules/core

include $(top_srcdir)/build/special.mk

