top_srcdir   = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
top_builddir = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
srcdir       = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules
builddir     = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules
VPATH        = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

