top_srcdir   = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
top_builddir = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
srcdir       = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules/arch/unix
builddir     = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules/arch/unix
VPATH        = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules/arch/unix

include $(top_srcdir)/build/special.mk

