top_srcdir   = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
top_builddir = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
srcdir       = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/server/mpm
builddir     = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/server/mpm
VPATH        = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
