top_srcdir   = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
top_builddir = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
srcdir       = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules/proxy
builddir     = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules/proxy
VPATH        = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules/proxy
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
#SUBDIRS = balancers
include $(top_srcdir)/build/special.mk
