top_srcdir   = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
top_builddir = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
srcdir       = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules/aaa
builddir     = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules/aaa
VPATH        = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules/aaa

include $(top_srcdir)/build/special.mk

