top_srcdir   = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
top_builddir = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
srcdir       = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/os
builddir     = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/os
VPATH        = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
