top_srcdir   = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
top_builddir = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
srcdir       = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/os/unix
builddir     = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/os/unix
VPATH        = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
