top_srcdir   = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
top_builddir = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
srcdir       = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules/filters
builddir     = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules/filters
VPATH        = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/modules/filters

include $(top_srcdir)/build/special.mk

