top_srcdir   = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
top_builddir = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd
srcdir       = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/server/mpm/event
builddir     = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/server/mpm/event
VPATH        = /Users/shivendrasrivastava/Documents/Apache_SAPFieldglass/httpd/server/mpm/event
include $(top_srcdir)/build/special.mk
